Repository erobot-dev/todo_app, pull requests merged in 2021-03, with the labels that each got.

#2 1 basic app setup
  assets/database/database.db
  assets/fonts/Kantumruy/Kantumruy-Bold.ttf
  assets/fonts/Kantumruy/Kantumruy-Light.ttf
  assets/fonts/Kantumruy/Kantumruy-Regular.ttf
  assets/fonts/Kantumruy/OFL.txt
  assets/fonts/Quicksand/OFL.txt
  assets/fonts/Quicksand/Quicksand-Bold.ttf
  assets/fonts/Quicksand/Quicksand-Light.ttf
  assets/fonts/Quicksand/Quicksand-Regular.ttf
  assets/translations/en.json
  assets/translations/km.json
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/app.dart
  lib/config/theme_config.dart
  lib/constants/config_constant.dart
  lib/helpers/app_helper.dart
  lib/main.dart
  lib/pages/detail_page.dart
  lib/pages/home_page.dart
  lib/widgets/t_task_tile.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: core, design

#4 close #3 update gitignore
  .gitignore
  ios/Podfile.lock
  pubspec.lock
Labels: core

#13 7 init database
  assets/database/database.db
  assets/database/database.sqbpro
  lib/database/database.dart
  lib/examples/examples.dart
  lib/main.dart
  lib/models/to_do_model.dart
  pubspec.yaml
  test/generate.dart
Labels: core

#17 5 t task tile
  lib/pages/home_page.dart
  lib/widgets/d_task_tile.dart
  lib/widgets/t_task_tile.dart
Labels: design

#16 6 main action button
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  lib/widgets/main_action_button.dart
Labels: design
